name: coldriver
description: "riverpod test lab"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0
  path_provider: ^2.1.5
  isar_community: ^3.3.0-dev.3
  isar_community_flutter_libs: ^3.3.0-dev.3
  page_route_animator: ^1.0.4
  mapbox_maps_flutter: ^2.12.0-rc.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: any
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  isar_community_generator: ^3.3.0-dev.3

flutter:
  uses-material-design: true

